# Generated by Django 2.2.9 on 2020-05-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reading', models.FloatField()),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('sensorType', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
